### ISSUE TITLE
Read Sequelize configuration

### ISSUE THREAD

**Issue by luismi930213** [orozco92/model-to-file#5]
Follow the next steps to configure the project and to check witch sequelize version is the user having:
1. Read .sequelizerc file
2. Read sequelize version
2.1 Version 6 >= load index in ./db/models (lookup at sequelize cli doc)
2.2 Version 6 < load index in ./models

**Comment by orozco92** [comment]
**./db/models** is an example configuration provided at the docs. Default value remains at ./models
